name: Github Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - '*oops2'

jobs:
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World!"
      - run: echo "Hello World! 2"
