name: Github Actions Demo

on:
  push:
    branches:
      - main
  pull-request:
    types:
      - opened
    branches:
      - '*oop'

jobs:
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World!"
      - run: echo "Hello World! 2"
